server:
  port: 8080
spring:
  application:
    name: sunny

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flying?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: shy20040609
    type: com.alibaba.druid.pool.DruidDataSource

  data:
    redis:
      host: shouit.eu.org
      port: 9998
      password: pro2024
      database: 0

      jedis:
        pool:
          max-wait: 1ms
          max-active: 8
          max-idle: 4
          min-idle: 0
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
